# Generated by Django 5.0.6 on 2024-07-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=100)),
                ('meeting_description', models.CharField(max_length=400)),
                ('meeting_link', models.CharField(max_length=250)),
                ('meeting_start', models.DateTimeField(blank=True)),
                ('meeting_end', models.DateTimeField(blank=True)),
            ],
        ),
    ]
