# Generated by Django 5.0.6 on 2024-07-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_start',
            field=models.DateTimeField(),
        ),
    ]
