# Generated by Django 5.0.6 on 2024-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meet', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=10)),
                ('Date', models.CharField(max_length=75)),
            ],
        ),
    ]
