# Generated by Django 5.0.6 on 2024-07-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meet', '0005_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
